// UI string dictionary for the bilingual atlas.
//
// Keys are flat (no nesting) so the React island can receive an explicit
// `t` prop with only the strings it needs without hauling the whole tree.
//
// Hebrew register: short, museum-quiet. Surnames stay Latin script inside
// Hebrew text (Israeli historical-writing convention). Lichen genera
// (Caloplaca, Verrucaria, …) stay Latin/italic — scientific names are
// never translated. Western numerals are kept (conventional in Israeli
// scientific writing).

import type { Locale } from './i18n';

export type StringKey = keyof typeof STRINGS.en;

export const STRINGS = {
  en: {
    // ─── Site identity / chrome ────────────────────────────────────────
    'brand.title': 'Lichen Atlas',
    'brand.subtitle': 'field documentation · Bezalel',
    'project.tagline': 'Lichen on Tombstone',
    'switcher.aria': 'Switch language',

    // ─── Nav ──────────────────────────────────────────────────────────
    'nav.lichens': 'Lichens',
    'nav.about': 'About',

    // ─── WIP banner ───────────────────────────────────────────────────
    'wip.label': 'WIP',
    'wip.body': 'Early prototype · AI-assisted documentation · biographies and lichen IDs are working hypotheses pending verification against printed sources.',

    // ─── Footer ───────────────────────────────────────────────────────
    'footer.col1.title': 'Lichen Atlas',
    'footer.col1.body': 'A field-research atlas of lichens colonizing historical cemeteries. Documentation generated by an AI-assisted pipeline; subject to morphology- and OCR-level verification.',
    'footer.col2.title': 'Project',
    'footer.col2.line1': 'Bio-Design — Bezalel M.Des',
    'footer.col2.line2': 'Maayan Magenheim',
    'footer.col3.title': 'Source & references',
    'footer.col3.line1': 'Galun & Haluwani (1977) — Lichens on tombstones in Jerusalem',
    'footer.col3.line2': 'Eisler & Gräf (2023) — Der historische Friedhof der Tempelgesellschaft in Jerusalem',

    // ─── Home (index.astro) ───────────────────────────────────────────
    'home.eyebrow': 'Field documentation · Bio-Design',
    'home.title.lead': 'Lichen Atlas',
    'home.title.sep': '—',
    'home.title.tail': 'life within the memory stone.',
    'home.lede': 'A growing record of lichen colonies on historical cemetery stones across Jerusalem. Each stone is a known-age test block; each colony, a slow re-writer of the inscription beneath it.',
    'home.attribution.prefix': 'Part of',
    'home.attribution.school': 'Bezalel Academy',
    'home.attribution.suffix': "'s M.Des Bio-Design course",
    'home.sites.heading': 'Field sites',
    'home.sites.count.suffix.one': 'site · more planned',
    'home.sites.count.suffix.many': 'sites · more planned',
    'home.sites.empty': 'No sites ingested yet. Run',
    'home.sites.empty.cmd': 'npm run ingest:templer',
    'home.sites.empty.tail': "from this project's root to populate the first site.",
    'home.sites.future.title': 'Future site',
    'home.sites.future.body': 'Har ha-Menukhot, Har ha-Zeitim, Wilhelma, Sarona — more cemeteries are planned. The atlas grows with each visit.',
    'home.sites.stones': 'stones',
    'home.sites.photos': 'photos',

    // ─── About (about.astro) ──────────────────────────────────────────
    'about.eyebrow': 'About',
    'about.title': 'Lichen on Tombstone',
    'about.intro': 'The Lichen Atlas is the public face of an ongoing bio-design research thread at Bezalel Academy (M.Des Industrial Design). The thread asks a single question:',
    'about.intro.bezalel': 'Bezalel Academy',
    'about.question': 'What happens in the top 2 millimetres of memory stone — between preservation and biological erosion — and how can a design intervention address this tension?',
    'about.methodology.title': 'Methodology',
    'about.methodology.intro': 'Each cemetery is documented by hand, photographed in two passes (full stone + lichen close-ups), and processed through an AI-assisted pipeline that:',
    'about.methodology.s1': 'Triages every photo into one of six classes (full stone, close-up, intro, etc.) and clusters them by stone',
    'about.methodology.s2': 'OCRs the inscription, translates it to English and Hebrew, and cross-references the name against the Templer Society registry and other sources',
    'about.methodology.s3': 'Identifies the lichen community in each photo to genus level (sometimes species), with explicit confidence labels',
    'about.methodology.s4': 'Records the result as one DETAILS.md per stone',
    'about.methodology.outro.lead': 'The output is intended to be both a',
    'about.methodology.outro.workingDataset': 'working dataset',
    'about.methodology.outro.mid': 'for further field research and a',
    'about.methodology.outro.contemplative': 'contemplative artefact',
    'about.methodology.outro.tail': '— a quiet, browsable record of a forgotten community and the lichens that have outlived it.',
    'about.confidence.title': 'Confidence & limits',
    'about.confidence.body': 'Every per-stone biography carries a confidence label and a callout asking for cross-reference against the definitive printed source: Eisler, J. & Gräf, U. (2023). Der historische Friedhof der Tempelgesellschaft in Jerusalem. Lichen IDs default to genus level — species claims are flagged and should be confirmed by microscopy + chemical spot tests.',
    'about.references.title': 'References',
    'about.credits.title': 'Credits',
    'about.credits.line1.lead': 'Field photography, research direction & design —',
    'about.credits.line1.name': 'Maayan Magenheim',
    'about.credits.line2': 'AI-assisted documentation pipeline — built as part of this Bio-Design thread.',

    // ─── Lichens page (lichens.astro) ─────────────────────────────────
    'lichens.eyebrow': 'Cross-site reference',
    'lichens.title': 'Lichen taxonomy',
    'lichens.lede': 'Every genus observed in the atlas, with its canonical color (the same dot you see in stone strata, chips, and biodiversity bars). Identification is genus-level by default; species-level guesses are listed where morphology was unambiguous.',
    'lichens.stones.suffix': 'stones',
    'lichens.species.heading': 'Species guesses observed',
    'lichens.bysite.label': 'By site:',
    'lichens.outro': 'The community profile is consistent with Galun & Haluwani (1977), Lichens on tombstones in Jerusalem: the dominant trio of Caloplaca + Aspicilia + Verrucaria with sub-dominant Lecanora, Candelariella and occasional foliose Xanthoria. Genus-level identification from photographs is reliable for distinctive morphologies; species-level requires microscopy and chemical spot tests (K, C, KC, P, UV).',

    // ─── Site detail page hero ────────────────────────────────────────
    'site.eyebrow.foundedPrefix': 'Field site · founded',
    'site.dl.stones': 'Stones',
    'site.dl.photos': 'Photos',
    'site.dl.range': 'Range',
    'site.dl.stoneAgeOldest': 'Stone age (oldest)',
    'site.dl.years.suffix': 'y',

    // ─── Stratigraphy explorer (left column) ──────────────────────────
    'explorer.sort.label': 'Sort',
    'explorer.sort.chronological': 'Chronological',
    'explorer.sort.coverage': 'Coverage',
    'explorer.sort.age': 'Age',
    'explorer.sort.surname': 'A → Z',
    'explorer.filter.lichen': 'Lichen',
    'explorer.filter.all': 'all',
    'explorer.confidence.label': 'Confidence',
    'explorer.confidence.high': 'high',
    'explorer.confidence.medium': 'medium',
    'explorer.confidence.low': 'low',
    'explorer.confidence.unknown': 'unknown',
    'explorer.unknownStone': 'Unknown stone',
    'explorer.biodiversity.label': 'Biodiversity in current view',
    'explorer.biodiversity.stones': 'stones',
    'explorer.biodiversity.none': 'none',
    'explorer.empty': 'Select a stone from the stratigraphy.',

    // ─── Stratigraphy explorer (right column / detail) ────────────────
    'detail.nee': 'née',
    'detail.born.short': 'b.',
    'detail.died.short': 'd.',
    'detail.age.prefix': '· age',
    'detail.stoneAge.prefix': 'stone',
    'detail.stoneAge.suffix': 'years old',
    'detail.photo.full': 'full stone',
    'detail.photo.closeup': 'lichen close-up',
    'detail.tab.inscription': 'inscription',
    'detail.tab.biography': 'biography',
    'detail.tab.lichens': 'lichens',
    'detail.tab.photos': 'photos',
    'detail.readIn': 'Read in',
    'detail.lang.en': 'English',
    'detail.lang.de': 'Original (German)',
    'detail.lang.he': 'עברית',
    'detail.inscription.empty': 'No transcription available.',
    'detail.biography.empty': '_No biographical content found in DETAILS.md._',
    'detail.dominant': 'Dominant:',
    'detail.coverage.prefix': '· coverage',
    'detail.lichens.empty': 'No lichen analysis recorded.',
    'detail.notable.label': 'Notable',
    'detail.stone.label': 'Stone:',
    'detail.verify.label': 'Verify:',
    'detail.verify.body': 'Cross-reference against Eisler & Gräf (2023) Der historische Friedhof der Tempelgesellschaft in Jerusalem.',
    'detail.registry.entry': 'Tempelgesellschaft registry entry',
  },

  he: {
    // ─── Site identity / chrome ────────────────────────────────────────
    'brand.title': 'אטלס החזזיות',
    'brand.subtitle': 'תיעוד שדה · בצלאל',
    'project.tagline': 'חזזית על מצבה',
    'switcher.aria': 'החלפת שפה',

    // ─── Nav ──────────────────────────────────────────────────────────
    'nav.lichens': 'חזזיות',
    'nav.about': 'אודות',

    // ─── WIP banner ───────────────────────────────────────────────────
    'wip.label': 'אב-טיפוס',
    'wip.body': 'אב-טיפוס מוקדם · תיעוד בסיוע בינה מלאכותית · הביוגרפיות וזיהויי החזזיות הן השערות עבודה הממתינות לאימות מול מקורות מודפסים.',

    // ─── Footer ───────────────────────────────────────────────────────
    'footer.col1.title': 'אטלס החזזיות',
    'footer.col1.body': 'אטלס מחקר-שדה של חזזיות המתיישבות על אבני בתי קברות היסטוריים. התיעוד נוצר על ידי צינור עבודה בסיוע בינה מלאכותית; טעון אימות ברמת מורפולוגיה ו-OCR.',
    'footer.col2.title': 'הפרויקט',
    'footer.col2.line1': 'ביו-דיזיין — בצלאל, תואר שני בעיצוב תעשייתי',
    'footer.col2.line2': 'מעיין מגנהיים',
    'footer.col3.title': 'מקור והפניות',
    'footer.col3.line1': 'Galun & Haluwani (1977) — חזזיות על מצבות בירושלים',
    'footer.col3.line2': 'Eisler & Gräf (2023) — בית הקברות ההיסטורי של חברת הטמפלרים בירושלים',

    // ─── Home (index.astro) ───────────────────────────────────────────
    'home.eyebrow': 'תיעוד שדה · ביו-דיזיין',
    'home.title.lead': 'אטלס החזזיות',
    'home.title.sep': '—',
    'home.title.tail': 'חיים בתוך אבן הזיכרון.',
    'home.lede': 'תיעוד הולך וגדל של מושבות חזזיות על מצבות היסטוריות בבתי קברות בירושלים. כל מצבה היא בלוק-בדיקה בעל גיל ידוע; כל מושבה — שכתבן איטי של הכתובת שמתחתיה.',
    'home.attribution.prefix': 'חלק מקורס',
    'home.attribution.school': 'בצלאל',
    'home.attribution.suffix': ', תואר שני בביו-דיזיין',
    'home.sites.heading': 'אתרי שדה',
    'home.sites.count.suffix.one': 'אתר · נוספים מתוכננים',
    'home.sites.count.suffix.many': 'אתרים · נוספים מתוכננים',
    'home.sites.empty': 'טרם נטענו אתרים. הריצו',
    'home.sites.empty.cmd': 'npm run ingest:templer',
    'home.sites.empty.tail': 'מתיקיית השורש של הפרויקט כדי לאכלס את האתר הראשון.',
    'home.sites.future.title': 'אתר עתידי',
    'home.sites.future.body': 'הר המנוחות, הר הזיתים, וילהלמה, שרונה — בתי קברות נוספים מתוכננים. האטלס גדל עם כל ביקור.',
    'home.sites.stones': 'מצבות',
    'home.sites.photos': 'תצלומים',

    // ─── About (about.astro) ──────────────────────────────────────────
    'about.eyebrow': 'אודות',
    'about.title': 'חזזית על מצבה',
    'about.intro': 'אטלס החזזיות הוא הפנים הציבוריים של חוט מחקר מתמשך בביו-דיזיין באקדמיה לאמנות ועיצוב בצלאל (תואר שני בעיצוב תעשייתי). חוט המחקר שואל שאלה אחת:',
    'about.intro.bezalel': 'בצלאל — אקדמיה לאמנות ועיצוב',
    'about.question': 'מה מתרחש בשני המילימטרים העליונים של אבן הזיכרון — בין שימור לבין שחיקה ביולוגית — וכיצד יכולה התערבות עיצובית לטפל במתח הזה?',
    'about.methodology.title': 'מתודולוגיה',
    'about.methodology.intro': 'כל בית קברות מתועד ידנית, מצולם בשני מעברים (מצבה שלמה + תקריבי חזזיות), ועובר עיבוד דרך צינור בסיוע בינה מלאכותית ש:',
    'about.methodology.s1': 'מסווג כל תצלום לאחת משש קטגוריות (מצבה שלמה, תקריב, פתיחה וכו׳) ומקבץ אותם לפי מצבה',
    'about.methodology.s2': 'מבצע OCR לכתובת, מתרגם לאנגלית ולעברית, ומצליב את השם מול רישום חברת הטמפלרים ומקורות נוספים',
    'about.methodology.s3': 'מזהה את קהילת החזזיות בכל תצלום ברמת הסוג (לעיתים המין), עם תוויות ודאות מפורשות',
    'about.methodology.s4': 'מתעד את התוצאה כקובץ DETAILS.md אחד לכל מצבה',
    'about.methodology.outro.lead': 'התוצר נועד לשמש בו-זמנית',
    'about.methodology.outro.workingDataset': 'מאגר עבודה',
    'about.methodology.outro.mid': 'למחקר-שדה נוסף וגם',
    'about.methodology.outro.contemplative': 'חפץ-התבוננות',
    'about.methodology.outro.tail': '— תיעוד שקט וניתן לעיון של קהילה נשכחת ושל החזזיות ששרדו אחריה.',
    'about.confidence.title': 'רמת ודאות ומגבלות',
    'about.confidence.body': 'כל ביוגרפיה למצבה נושאת תווית ודאות וקריאה להצלבה מול המקור המודפס המוסמך: Eisler, J. & Gräf, U. (2023). Der historische Friedhof der Tempelgesellschaft in Jerusalem. זיהוי החזזיות הוא ברמת הסוג כברירת מחדל — קביעות ברמת המין מסומנות ויש לאמת אותן באמצעות מיקרוסקופיה ובדיקות-נקודה כימיות.',
    'about.references.title': 'מקורות',
    'about.credits.title': 'קרדיטים',
    'about.credits.line1.lead': 'צילום שדה, הכוונה מחקרית ועיצוב —',
    'about.credits.line1.name': 'מעיין מגנהיים',
    'about.credits.line2': 'צינור תיעוד בסיוע בינה מלאכותית — נבנה כחלק מחוט המחקר בביו-דיזיין.',

    // ─── Lichens page (lichens.astro) ─────────────────────────────────
    'lichens.eyebrow': 'הפניה רב-אתרית',
    'lichens.title': 'טקסונומיה של החזזיות',
    'lichens.lede': 'כל סוג שנצפה באטלס, עם הצבע הקנוני שלו (אותה נקודה שמופיעה בשכבות המצבות, בז׳יטונים ובסרגלי המגוון הביולוגי). הזיהוי הוא ברמת הסוג כברירת מחדל; השערות ברמת המין מצוינות במקרים שבהם המורפולוגיה הייתה חד-משמעית.',
    'lichens.stones.suffix': 'מצבות',
    'lichens.species.heading': 'השערות מינים שנצפו',
    'lichens.bysite.label': 'לפי אתר:',
    'lichens.outro': 'פרופיל הקהילה עקבי עם Galun & Haluwani (1977), חזזיות על מצבות בירושלים: שלישיית הסוגים הדומיננטית Caloplaca + Aspicilia + Verrucaria עם Lecanora, Candelariella כתת-דומיננטיות ו-Xanthoria עליתית מדי פעם. זיהוי ברמת הסוג מתצלומים אמין למורפולוגיות ייחודיות; רמת המין דורשת מיקרוסקופיה ובדיקות-נקודה כימיות (K, C, KC, P, UV).',

    // ─── Site detail page hero ────────────────────────────────────────
    'site.eyebrow.foundedPrefix': 'אתר שדה · נוסד',
    'site.dl.stones': 'מצבות',
    'site.dl.photos': 'תצלומים',
    'site.dl.range': 'טווח',
    'site.dl.stoneAgeOldest': 'גיל מצבה (העתיקה ביותר)',
    'site.dl.years.suffix': 'שנים',

    // ─── Stratigraphy explorer (left column) ──────────────────────────
    'explorer.sort.label': 'מיון',
    'explorer.sort.chronological': 'כרונולוגי',
    'explorer.sort.coverage': 'כיסוי',
    'explorer.sort.age': 'גיל',
    'explorer.sort.surname': 'א — ת',
    'explorer.filter.lichen': 'חזזית',
    'explorer.filter.all': 'הכול',
    'explorer.confidence.label': 'רמת ודאות',
    'explorer.confidence.high': 'גבוהה',
    'explorer.confidence.medium': 'בינונית',
    'explorer.confidence.low': 'נמוכה',
    'explorer.confidence.unknown': 'לא ידוע',
    'explorer.unknownStone': 'מצבה לא מזוהה',
    'explorer.biodiversity.label': 'מגוון ביולוגי בתצוגה הנוכחית',
    'explorer.biodiversity.stones': 'מצבות',
    'explorer.biodiversity.none': 'אין',
    'explorer.empty': 'בחרו מצבה מתוך השכבות.',

    // ─── Stratigraphy explorer (right column / detail) ────────────────
    'detail.nee': 'לבית',
    'detail.born.short': 'נ׳',
    'detail.died.short': 'נפ׳',
    'detail.age.prefix': '· בן/בת',
    'detail.stoneAge.prefix': 'המצבה בת',
    'detail.stoneAge.suffix': 'שנים',
    'detail.photo.full': 'מצבה שלמה',
    'detail.photo.closeup': 'תקריב חזזית',
    'detail.tab.inscription': 'כתובת',
    'detail.tab.biography': 'ביוגרפיה',
    'detail.tab.lichens': 'חזזיות',
    'detail.tab.photos': 'תצלומים',
    'detail.readIn': 'קריאה ב',
    'detail.lang.en': 'אנגלית',
    'detail.lang.de': 'מקור (גרמנית)',
    'detail.lang.he': 'עברית',
    'detail.inscription.empty': 'אין תעתיק זמין.',
    'detail.biography.empty': '_לא נמצא תוכן ביוגרפי בקובץ DETAILS.md._',
    'detail.dominant': 'דומיננטית:',
    'detail.coverage.prefix': '· כיסוי',
    'detail.lichens.empty': 'לא נרשמה ניתוח חזזיות.',
    'detail.notable.label': 'בולט',
    'detail.stone.label': 'אבן:',
    'detail.verify.label': 'אימות:',
    'detail.verify.body': 'יש להצליב מול Eisler & Gräf (2023) Der historische Friedhof der Tempelgesellschaft in Jerusalem.',
    'detail.registry.entry': 'רישום חברת הטמפלרים, ערך',
  },
} as const satisfies Record<Locale, Record<string, string>>;

/** Lookup a localized string. Falls back to English if the key is missing. */
export function t(key: StringKey, locale: Locale): string {
  const bag = STRINGS[locale] as Record<string, string>;
  return bag[key] ?? STRINGS.en[key];
}

/**
 * Build a small bag of strings keyed by their flat key — useful when
 * passing into a React island so the island gets a plain object, not the
 * whole locale tree.
 */
export function tBag<K extends StringKey>(keys: readonly K[], locale: Locale): Record<K, string> {
  const out = {} as Record<K, string>;
  for (const k of keys) out[k] = t(k, locale);
  return out;
}

/** Keys consumed by the StratigraphyExplorer React island. */
export const EXPLORER_KEYS = [
  'site.dl.years.suffix',
  'explorer.sort.label',
  'explorer.sort.chronological',
  'explorer.sort.coverage',
  'explorer.sort.age',
  'explorer.sort.surname',
  'explorer.filter.lichen',
  'explorer.filter.all',
  'explorer.confidence.label',
  'explorer.confidence.high',
  'explorer.confidence.medium',
  'explorer.confidence.low',
  'explorer.confidence.unknown',
  'explorer.unknownStone',
  'explorer.biodiversity.label',
  'explorer.biodiversity.stones',
  'explorer.biodiversity.none',
  'explorer.empty',
  'detail.nee',
  'detail.born.short',
  'detail.died.short',
  'detail.age.prefix',
  'detail.stoneAge.prefix',
  'detail.stoneAge.suffix',
  'detail.photo.full',
  'detail.photo.closeup',
  'detail.tab.inscription',
  'detail.tab.biography',
  'detail.tab.lichens',
  'detail.tab.photos',
  'detail.readIn',
  'detail.lang.en',
  'detail.lang.de',
  'detail.lang.he',
  'detail.inscription.empty',
  'detail.biography.empty',
  'detail.dominant',
  'detail.coverage.prefix',
  'detail.lichens.empty',
  'detail.notable.label',
  'detail.stone.label',
  'detail.verify.label',
  'detail.verify.body',
  'detail.registry.entry',
] as const satisfies readonly StringKey[];

export type ExplorerStrings = Record<(typeof EXPLORER_KEYS)[number], string>;

